### ISSUE TITLE
Add support for kitty (--type=overlay) when [[ -z $TMUX ]]

### ISSUE THREAD

**Issue by megalithic** [trygveaa/weechat-fzf#1]
Love this plugin!

I've been happily using it for a bit now, however, I've recently started to move away from tmux to use kitty primarily (not necessarily needing all the features of a terminal multiplexer, other than the "window management" and TPM things).

I've been tinkering with the plugin to add kitty support to basically do the same as it is now but a kitty overlay instead. 

I was wondering if you've looked into this/would look into this/would consider a PR if I get it working correctly?

Thanks for all you do on weechat and more.

**Comment by megalithic** [comment]
Here's a gist of what i've got so far. it's mega hacky as I don't typically write python and honestly haven't tinkered a ton with kitty's capabilities:

https://gist.github.com/megalithic/bca281cc0ccec28d5fe902bf15fcf8ee

**Comment by megalithic** [comment]
@trygveaa I was wondering if you'd have time to review the above gist for such functionality. I'd absolutely love to have weechat-fzf capabilities, but with fzf + kitty overlay or pane; when not in tmux.

**Comment by trygveaa** [comment]
Hi, yes sure, supporting kitty in addition to tmux would be nice. I took a look at your gist now, is it working for you? `--` is not accepted as an option to fzf here, and even if I remove it the buffer list is not sent to fzf for me.

**Comment by megalithic** [comment]
Unfortunately no, i'm seeing the same. Been fiddling with it and can't seem to get the right incantation to send the bufferlist to kitty's inputs :(

**Comment by trygveaa** [comment]
As far as I can see, kitty doesn't support sending the stdin to the process it launches, but I figured out you can use `FZF_DEFAULT_COMMAND` to pass in the buffer list like this:

```
kitty @ launch --env FZF_DEFAULT_COMMAND='echo -e "buffer1\nbuffer2"' fzf
```

However, getting the result you selected in fzf back to weechat is more tricky. I haven't found a way to do that yet.

**Comment by megalithic** [comment]
This is brilliant work! I hate we can't use kitty's stdin/out mechanisms directly. There does seem to be a way to get last-cmd output as stdin to kitty (https://sw.kovidgoyal.net/kitty/remote-control/?highlight=stdin#cmdoption-kitty-launch-stdin-source), but clearly, more work/research to do. :)

**Comment by trygveaa** [comment]
> There does seem to be a way to get last-cmd output as stdin to kitty (https://sw.kovidgoyal.net/kitty/remote-control/?highlight=stdin#cmdoption-kitty-launch-stdin-source), but clearly, more work/research to do. :)

This is the output the last command printed to the terminal, so to be able to use this I think we would have to spawn a shell in the overlay, run a command to print the buffers, and then run fzf, which seems more impractical. It also doesn't seem to work when run via the remote control, only when bound to a key.

**Comment by megalithic** [comment]
I've switched back to tmux for the foreseeable future; there are just too many usages where i haven't been able to create/find suitable analogs for feature parity between tmux/kitty.

**Comment by trygveaa** [comment]
Alright, too bad. I also use tmux because I need a persistent session on the server (and because I also connect to it from my phone where I don't/can't use kitty).

**Comment by megalithic** [comment]
That's largely my use-case too; that and making extensive use of sessions/tmuxinator for various projects for work/personal. I don't want kitty to take on being a multiplexer too, though I would love for it to allow for some way to work better with std in/out and maybe even have kitty run as a daemon to have long-running "sessions" that i can switch to/from.
